config/routes.rb
MiniBlog::Application.routes.draw do
  
  resource :session, :only => [:new, :create, :destroy]
  
  resources :admins

  resources :posts do
    resources :comments
  end

  root :to => 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :author, :body
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  skip_before_filter :require_admin, :except => [:edit, :update, :destroy]

  before_filter :load_post
  # GET /comments
  # GET /comments.json
  def index
    @comments = @post.comments

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = @post.comments.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = @post.comments.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = @post.comments.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = @post.comments.build(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: [@post, @comment] }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = @post.comments.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @post, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to post_comments_url(@post) }
      format.json { head :no_content }
    end
  end

private

  def load_post
    @post =Post.find(params[:post_id])
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<blockquote>
  <small>
    <strong><%= comment.author %></strong>
    -
    <%=l comment.created_at, :format => :long %>
    -
    <%= link_to 'Edit', edit_post_comment_path(@post, comment) %>
    -
    <%= link_to 'Destroy', [@post, comment], method: :delete, data: { confirm: 'Are you sure?' } %>
  </small>
  <%= simple_format comment.body %>
</blockquote>

app/views/comments/_form.html.erb
<%= form_for([@post, @comment], :html => {:class => 'well span9'}) do |f| %>
  <h4><i class="icon-plus"></i>Add a comment:</h4>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:
      </h2>
      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author, :class => 'span9' %>
  </div>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body, :class => 'span9', :rows => 5 %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'btn btn-primary pull-right'%>
  </div>
<% end %>

app/views/comments/edit.html.erb
<%= link_to @post, :class => 'btn btn-sucess' do %>
	<i class="icon-arrow-left">&nbsp;Back to Post</i>
<% end %>

<h1>Editing comment for <%= @post.title %></h1>
<%= render 'form' %>

app/views/comments/index.html.erb
<h1>Listing comments for <%= @post.title %></h1>

<p>
  <%= link_to 'Back to post index', posts_path %>
  |
  <%= link_to 'Back to post', @post %>
<table>
  <tr>
    <th>Author</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.author %></td>
    <td><%= comment.body %></td>
    <td><%= link_to 'Show', [@post, comment] %></td>
    <td><%= link_to 'Edit', edit_post_comment_path(@post, comment) %></td>
    <td><%= link_to 'Destroy', [@post, comment], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_post_comment_path(@post) %>

app/views/comments/new.html.erb
<h1>New comment for <%= @post.title %></h1>

<%= render 'form' %>

<%= link_to 'Back', post_comments_path(@post) %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Author:</b>
  <%= @comment.author %>
</p>

<p>
  <b>Body:</b>
  <%= @comment.body %>
</p>


<%= link_to 'Edit', edit_post_comment_path(@post, @comment) %> |
<%= link_to 'Back', post_comments_path(@post) %>