config/routes.rb
MiniBlog::Application.routes.draw do
  
  resource :session, :only => [:new, :create, :destroy]
  
  resources :admins

  resources :posts do
    resources :comments
  end

  root :to => 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title, :category

  validates :title, :category, :presence => true
  validates :title, :uniqueness => true

  before_validation :apply_title_format

  has_many :comments

private

  def apply_title_format
  	self[:title] = self[:title].strip.capitalize
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    skip_before_filter :require_admin, :only => [:index, :show]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order("created_at DESC").all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comment = @post.comments.new
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :title, :class => 'span12', :placeholder => "Write a title...", :style => 'font-size: 30px; line-height: 30px; height: 30px' %>
  </div>
    <div class="field">
    <%= f.text_area :body, :class => 'span12', :placeholder => "Write something awesome..."%>
  </div>
  <div class="row">
    <div class="field span7">
      <%= f.label :category %>
      <%= f.text_field :category, :class => 'span7' %>
    </div>
    <div class="actions pull-right" style="padding-top: 10px">
      <%= f.submit :class => 'btn btn-primary btn-large' %>
      or
      <%= link_to "Cancel", :back %>
    </div>
  </div>
<% end %>

app/views/posts/_post.html.erb
<article pubdate>
  <header>
    <h1><%= link_to post.title, post %></h1>
    <p>Created on <time><%=l post.created_at, :format => :long %></time></p>
  </header>

  <%=simple_format post.body %>

  <footer>
    <%= link_to 'Show', post %> |
    <%= link_to 'Edit', edit_post_path(post) %> |
    <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %> |
    <%= link_to pluralize(post.comments.count, "comment"), post_path(post)+"#comments" %>
  </footer>
</article>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= link_to new_post_path, :class => 'btn btn-success pull-right' do %>
  <i class="icon-edit"></i> New Post
<% end %>
<section>
  <%= render :partial => 'post', :collection => @posts %>
</section>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<%= render :partial => 'post', :object => @post %>
<h4><a name= "comments"></a>Comments</h4>
<%= render :partial => 'comments/comment',
           :collection => @post.comments.order("created_at ASC") %>
<%= render :partial => 'comments/form' %>