config/routes.rb
MiniBlog::Application.routes.draw do
  
  resource :session, :only => [:new, :create, :destroy]
  
  resources :admins

  resources :posts do
    resources :comments
  end

  root :to => 'posts#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MiniBlog" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->
<!--se han eliminado las líneas de %= favicon_link_tag ... -->

    <%= stylesheet_link_tag "application", :media => "all" %>

  </head>
  <body>

    <div class="navbar">
      <div class="navbar-inner">
        <%= link_to "MiniBlog", root_path, :class => 'brand' %>
        <ul class= "nav pull-right">
          <% if current_admin %>
            <li><%= link_to "Admins", admins_path %></li>
            <li><%= link_to "Log out", session_path, :method => :delete, :confirm => "Are you sure?" %></li>
          <% else %>
            <li><%= link_to "Log in", new_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="span12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>
          Fork <%= link_to "MiniBlog at GitHub", "https://github.com/Willazo/mini-blog"%>
          |
          Created by <%= link_to "Willazo"%> in 2013
        </p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/layouts/application_old.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MiniBlog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="menu" style="float: right">
  <%= link_to "Posts", posts_path %>
  |
  <% if current_admin %>
    <%= link_to "Admins", admins_path %>
    |
    <%= link_to "Log out", session_path, :method => :delete, :confirm => "Are you sure?" %>
  <% else %>
    <%= link_to "Log in", new_session_path %>
  <% end %>
</div>

<%= yield %>

</body>
</html>